version: '3'
services:
  web:
    build: .
    expose:
      - 5000
    restart: always
    command: gunicorn -b 0.0.0.0:5000 app:app
    volumes:
      - ./app:/app
  postgre:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=dijam
      - POSTGRES_USER=dijam
      - POSTGRES_DB=dijam
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    depends_on:
      - web